#!/usr/bin/env php
<?php
/**
 * A series of commands to work with Aura library repos.
 * 
 * @todo A "validate" command to validate a library repo; composer, travis,
 * directories, etc.
 */
// strictest error reporting
error_reporting(E_ALL);

// name => class
$commands = [
    'issues'        => 'Issues',
    'packagist'     => 'Packagist',
    'release'       => 'Release',
    'repos'         => 'Repos',
    'system-status' => 'SystemStatus',
    'travis'        => 'Travis',
];

// config file
$config_file = $_SERVER['HOME'] . '/.aurarc';
if (! file_exists($config_file) || ! is_readable($config_file)) {
    echo "Please create '$file' with your github username:password authorization." . PHP_EOL;
    die(1);
}

// autoloading
spl_autoload_register(function ($class) {
    include __DIR__ . "/$class.php";
});

// shift off the script name
array_shift($argv);

// was a command specified?
$name = array_shift($argv);
if (! $name) {
    echo "Command not specified." . PHP_EOL;
    exit(1);
}

// does the command exist?
if (! isset($commands[$name])) {
    echo "Command not recognized." . PHP_EOL;
    exit(1);
}

// does the class exist?
$class = $commands[$name];
if (! class_exists($class)) {
    echo "Command not defined." . PHP_EOL;
    exit(1);
}

// instantiate and invoke the class with modified argv
$config = new Config(parse_ini_file($config_file));
$command = new $class($config);
$command($argv);
exit(0);
